version: "3"
services:
    db:
        image: mariadb:10.3.15
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: test_recrutement
        ports:
            - "3306:3306"

    php:
        build:
            context: ./
            dockerfile: php/Dockerfile
        links:
            - db:mariadb
        volumes:
            - ./app:/app

    httpd:
        image: httpd:latest
        ports:
            - "80:80"
        volumes:
            - ./app:/app
            - ./httpd/conf:/usr/local/apache2/conf
            - ./logs:/logs
        links:
            - php
