doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: utf8mb4 # utf8 for PostgreSQL
        default_table_options:
            charset: utf8mb4 # utf8 for PostgreSQL
            collate: utf8mb4_unicode_ci # utf8_unicode_ci for PostgreSQL
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
